[Sparkle.xcodeproj] Remove duplicate Sparkle.strings from project to fix build "xcodebuild" errors.
There's some sort of race condition since the building happens in parallel
and it randomly fails when copying the Sparkle.strings from the various
translations. An example error is:

error: failed to remove build/Release/Sparkle.framework/Versions/A/Resources/nl.lproj/Sparkle.strings: “Sparkle.strings” couldn’t be removed.